version: "3.9"

services:
  web:
    container_name: jeopardy
    image: pmineev/jeopardy
    build:
      context: .
      target: backend-prod
      args:
        - HOST
    command : daphne -b 0.0.0.0 -p 8000 backend.config.asgi:application
    ports:
      - "80:8000"