version: "3.9"

volumes:
  postgres_data:
  redis_data:

services:
  redis:
    image: redis:6.2.6
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  db:
    image: postgres:13.6-alpine
    container_name: postgres
    env_file:
      - ./db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: web
    env_file:
      - ./db.env
      - ./django.env
    depends_on:
      - db
      - redis
