version: "3.9"

services:
  web:
    container_name: web-prod
    image: jeopardy-web
    build:
      context: .
      target: backend-prod
      args:
        HOST: "195.133.147.176"
    environment:
      HOST: "195.133.147.176"
    command : >
      bash -c "python manage.py makemigrations backend
      && python manage.py migrate
      && daphne -b 0.0.0.0 -p 8000 backend.config.asgi:application"
    ports:
      - "80:8000"