openapi: '3.0.3'

info:
  title: Jeopardy REST API
  version: '1.0.0'
  description: |
    API для синхронных событий.

servers:
- url: http://127.0.0.1:8000/api
  description: Сервер для разработки

security:
- jwt_auth: []

paths:
  /users/:
    post:
      summary: Регистрация пользователя
      requestBody:
        description: Данные для регистрации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerUserCredentials'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
        '409':
          description: |
            Регистрация пользователя отклонена.

            Возможные причины:
            - пользователь с указанным именем уже существует;
            - пользователь с указанным ником уже существует.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/requestRejectReason'
        '422':
          description: Некорректные данные
      security: []
      tags:
      - users

  /users/{username}/:
    get:
      summary: Получение информации о пользователе
      parameters:
      - name: username
        in: path
        description: Имя пользователя
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '403':
          description: Доступ запрещен
      tags:
      - users

    patch:
      tags:
      - users
      summary: Изменение информации о пользователе
      parameters:
      - name: username
        in: path
        description: Имя пользователя
        required: true
        schema:
          type: string
      requestBody:
        description: Изменяемые данные
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/changeUserCredentials'
      responses:
        '204':
          description: Информация изменена
        '422':
          description: Некорректные данные

  /sessions:
    post:
      tags:
      - sessions
      summary: Аутентификация пользователя
      requestBody:
        description: Учетные данные пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUserCredentials'
      responses:
        '200':
          description: Аутентификация прошла успешно
          content:
            application/json:
              schema:
                description: JWT-токены
                type: object
                required:
                - access
                - refresh
                properties:
                  refresh:
                    description: refresh-токен
                    type: string
                  access:
                    description: access-токен
                    type: string
        '401':
          description: Неверные учетные данные
        '422':
          description: Некорректные данные
      security: []

  /sessions/new_token/:
    post:
      tags:
      - sessions
      summary: Получение нового access-токена
      requestBody:
        description: Действующий refresh-токен
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - refresh
              properties:
                refresh:
                  description: refresh-токен
                  type: string
      responses:
        '201':
          description: Новый access-токен успешно создан
          content:
            application/json:
              schema:
                description: Новый access-токен
                type: object
                required:
                - access
                properties:
                  access:
                    description: access-токен
                    type: string
      security: []

  /games/:
    get:
      tags:
      - games
      summary: Получение списка игр
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: Список описаний игр
                type: object
                properties:
                  descriptions:
                    type: array
                    items:
                      description: Описание игры
                      type: object
                      additionalProperties: false
                      required:
                      - name
                      - author
                      - roundsCount
                      properties:
                        name:
                          description: Название игры
                          type: string
                        author:
                          description: Автор игры
                          type: string
                        roundsCount:
                          description: Количество раундов
                          type: integer
                          minimum: 2

    post:
      tags:
      - games
      summary: Создать новую игру
      requestBody:
        required: true
        description: Данные игры
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/game'
      responses:
        '201':
          description: Игра успешно сохранена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameState'
        '409':
          description: Игра с таким именем уже существует
        '422':
          description: Некорректные данные

  /game_sessions/:
    get:
      tags:
      - game_sessions
      summary: Получение списка игровых сессий
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: Список игровых сессий
                type: object
                properties:
                  descriptions:
                    type: array
                    items:
                      $ref: '#/components/schemas/gameSessionDescription'

    post:
      tags:
      - game_sessions
      summary: Создание игровой сессии
      requestBody:
        description: Параметры игровой сессии
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createGameSession'
      responses:
        '201':
          description: Игровая сессия создана
        '409':
          description: Пользователь уже играет
        '422':
          description: Некорректные данные

  /game_sessions/id/:
    get:
      tags:
      - game_sessions
      summary: Получение игроком идентификатора игровой сессии
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: Идентификатор игровой сессии
                type: object
                required:
                - id
                properties:
                  id:
                    type: integer
                    minimum: 1
        '404':
          description: Пользователь не играет

  /game_sessions/{game_session_id}/:
    get:
      tags:
      - game_sessions
      summary: Получение игроком текущего состояния игровой сессии
      parameters:
      - name: game_session_id
        in: path
        description: Идентификатор игровой сессии
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameState'
        '403':
          description: Пользователя нет в указанной игровой сессии

  /game_sessions/{game_session_id}/actions/join/:
    post:
      tags:
      - game_sessions
      summary: Присоединение к игре
      parameters:
      - name: game_session_id
        in: path
        description: Идентификатор игровой сессии
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Пользователь успешно присоединился к игре
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameState'
        '409':
          description: |
            Пользователь не присоединен к игре.

            Возможные причины:
            - достигнуто максимальное количество игроков в сессии;
            - пользователь уже есть в другой сессии.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/requestRejectReason'

  /game_sessions/{game_session_id}/actions/leave/:
    post:
      tags:
      - game_sessions
      summary: Выход из игры
      parameters:
      - name: game_session_id
        in: path
        description: Идентификатор игровой сессии
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Пользователь успешно вышел из игры
        '403':
          description: Пользователя нет в указанной игровой сессии

  /game_sessions/{game_session_id}/current_question/:
    post:
      tags:
      - game_sessions
      summary: Выбор текущего вопроса
      parameters:
      - name: game_session_id
        in: path
        description: Идентификатор игровой сессии
        schema:
          type: integer
      requestBody:
        description: Параметры вопроса
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/questionChoice'
      responses:
        '201':
          description: Текущий вопрос выбран
        '403':
          description: |
            Выбор вопроса отклонен.

            Возможные причины:
            - пользователя нет в указанной игровой сессии;
            - пользователь не является текущим игроком;
            - текущая стадия игры не предполагает выбора ответа;
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/requestRejectReason'
        '422':
          description: Некорректные данные

  /game_sessions/{game_session_id}/answer/:
    post:
      tags:
      - game_sessions
      summary: Отправка ответа на текущий вопрос
      parameters:
      - name: game_session_id
        in: path
        description: Идентификатор игровой сессии
        required: true
        schema:
          type: string
      requestBody:
        description: Ответ на вопрос
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/playerAnswer'
      responses:
        '201':
          description: OK
        '403':
          description: |
            Отправка ответа отклонена.

            Возможные причины:
            - пользователя нет в указанной игровой сессии;
            - текущая стадия игры не предполагает ответа на вопрос.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/requestRejectReason'
        '422':
          description: Некорректные данные

components:
  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    registerUserCredentials:
      type: object
      required:
      - password
      - username
      properties:
        username:
          description: Имя пользователя
          type: string
        nickname:
          description: Ник пользователя
          type: string
        password:
          description: Пароль пользователя
          type: string

    changeUserCredentials:
      type: object
      properties:
        nickname:
          description: Ник пользователя
          type: string
        password:
          description: Пароль пользователя
          type: string

    loginUserCredentials:
      type: object
      required:
      - password
      - username
      properties:
        username:
          description: Имя пользователя
          type: string
        password:
          description: Пароль пользователя
          type: string

    user:
      description: Информация о пользователе
      type: object
      required:
      - username
      - nickname
      properties:
        username:
          description: Имя пользователя
          type: string
        nickname:
          description: Ник пользователя
          type: string

    game:
      description: Игра
      type: object
      additionalProperties: false
      required:
      - name
      - rounds
      - finalRound
      properties:
        name:
          description: Название игры
          type: string
        rounds:
          description: Раунды игры
          type: array
          items:
            $ref: '#/components/schemas/round'
        finalRound:
          $ref: '#/components/schemas/question'

    round:
      description: Раунд
      type: object
      required:
      - themes
      properties:
        themes:
          description: Темы раунда
          type: array
          items:
            $ref: '#/components/schemas/theme'

    theme:
      description: Тема
      type: object
      required:
      - name
      - questions
      properties:
        name:
          description: Название темы
          type: string
        questions:
          description: Вопросы темы
          type: array
          items:
            $ref: '#/components/schemas/question'

    question:
      description: Вопрос
      type: object
      required:
      - text
      - answer
      - value
      properties:
        text:
          description: Текст вопроса
          type: string
        answer:
          description: Ответ на вопрос
          type: string
        value:
          description: Стоимость вопроса
          type: integer
          minimum: 0

    gameSessionDescription:
      description: Описание игровой сессии
      type: object
      additionalProperties: false
      required:
      - id
      - creator
      - gameName
      - maxPlayers
      - currentPlayers
      properties:
        id:
          description: Идентификатор игровой сессии
          type: integer
          minimum: 1
        creator:
          description: Ник создателя игровой сессии
          type: string
        gameName:
          description: Название игры
          type: string
        maxPlayers:
          description: Максимальное количество игроков
          type: integer
          minimum: 2
        currentPlayers:
          description: Текущее количество игроков
          type: integer
          minimum: 1

    createGameSession:
      description: Описание игровой сессии
      type: object
      required:
      - gameName
      - maxPlayers
      properties:
        gameName:
          description: Название игры
          type: string
        maxPlayers:
          description: Максимальное количество игроков
          type: integer
          minimum: 2

    gameState:
      description: Состояние игровой сессии
      type: object
      additionalProperties: false
      required:
      - stage
      - players
      properties:
        stage:
          description: Стадия игры
          type: string
        players:
          description: Игроки
          type: array
          items:
            $ref: '#/components/schemas/player'
        currentRound:
          allOf:
          - $ref: '#/components/schemas/round'
          - type: object
            required:
            - order
            properties:
              order:
                description: Индекс раунда
                type: integer
                minimum: 0
        currentPlayer:
          $ref: '#/components/schemas/playerNickname'
        currentQuestion:
          description: Текущий вопрос
          type: object
          required:
          - text
          - value
          properties:
            text:
              description: Текст вопроса
              type: string
            value:
              description: Стоимость вопроса
              type: integer
              minimum: 0
            themeOrder:
              description: Индекс темы вопроса
              type: integer
              minimum: 0
            questionOrder:
              description: Индекс вопроса в теме
              type: integer
              minimum: 0

    player:
      description: Игрок
      type: object
      required:
      - nickname
      - score
      properties:
        nickname:
          $ref: '#/components/schemas/playerNickname'
        score:
          description: Счет игрока
          type: integer
          minimum: 0
        answer:
          $ref: '#/components/schemas/answer'

    answer:
      description: Ответ
      type: object
      required:
      - text
      - isCorrect
      properties:
        text:
          description: Текст ответа
          type: string
        isCorrect:
          description: Корректность ответа
          type: boolean

    playerNickname:
      description: Ник игрока
      type: string

    questionChoice:
      required:
      - themeOrder
      - questionOrder
      type: object
      properties:
        themeOrder:
          description: Индекс темы вопроса
          type: integer
          minimum: 0
        questionOrder:
          description: Индекс вопроса в теме
          type: integer
          minimum: 0

    playerAnswer:
      required:
      - answer
      type: object
      properties:
        answer:
          description: Текст ответа
          type: string

    requestRejectReason:
      description: Причина отклонения запроса
      type: object
      required:
      - reason
      properties:
        reason:
          type: string

